# Generated by Django 4.2.7 on 2023-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_application',
            name='Candidate_Picture',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/', verbose_name='Candidate Pic'),
        ),
    ]
