# Generated by Django 4.2.7 on 2023-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_candidate_application_candidate_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='CNIC',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Party',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
