# Generated by Django 4.2.7 on 2023-12-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_alter_candidate_cnic_alter_candidate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_application',
            name='disclamer',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='candidate_application',
            name='symbol_image',
            field=models.ImageField(blank=True, null=True, upload_to='symbol_images/', verbose_name='Symbol Pic'),
        ),
    ]
