# Generated by Django 4.2.7 on 2023-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_votingperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='total_vote',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
