# Generated by Django 4.2.7 on 2023-12-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0007_position_total_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate_application',
            old_name='symbol_image',
            new_name='Symbol_Picture',
        ),
        migrations.RenameField(
            model_name='candidate_application',
            old_name='disclamer',
            new_name='disclaimer',
        ),
    ]
