# Generated by Django 4.2.7 on 2023-12-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0008_rename_symbol_image_candidate_application_symbol_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_time', models.DateTimeField()),
            ],
        ),
    ]
